### ISSUE TITLE
How to register/call different micro services?

### ISSUE THREAD

**Issue by approots** [onbjerg/micro-auth-example#1]
From the example, it would appear that every micro service would need to be listening on a different port?

**Comment by onbjerg** [comment]
Hey,

This is not really a job for micro. Service discovery is a different subject, and there are multiple ways to solve it.

Some people run their microservices in Docker containers which then assign the port to a random external port. This is then registered via different mechanisms to a load balancer that routes traffic (see for example _services_ in Kubernetes).

Other people simply have the containers register themselves in a key/value store like Consul or etcd with their IP address, service name, version and port. A routing layer then uses this information to hit the correct microservice.

Does this somewhat help you?

**Comment by approots** [comment]
Great explanation. Thank you.

**Comment by onbjerg** [comment]
Great! No worries. If you have any other questions then I'm available on the [ZEIT Community Slack](https://zeit.chat) as @notbjerg 😊
